# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2f0e4696e9b7ef5c0e3369eefc7d70c3e0e81ce3097bf99104e88b195b3e7d0d61bfb0037bec0c6cf81d8802330a1f5fa6dd755cf2735a38fd2ee247afaa3e4

test:
  secret_key_base: c4931a7057c6508ebed46d98683d95a6e0b21b608ab7643d79a8a43d2483183df1d3bc4939cccef535118b2afb34e07c98a33984f529ed030d248c6c73d2b841

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
